# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  buildAndTest:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: jethred
          password: $DOCKER_PASS
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      # build and push Docker image
      - run: |
          TAG=latest
          docker build -t jethred/react-test:$TAG -f Dockerfile.dev -f ./client/Dockerfile.dev ./client
          docker run -e CI=true jethred/react-test:$TAG npm run test

  buildProdImages:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: jethred
          password: $DOCKER_PASS
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      # build and push Docker images
      - run: |
          TAG=latest
          docker build -t jethred/multi-client:$TAG ./client
          docker build -t jethred/multi-nginx:$TAG ./nginx
          docker build -t jethred/multi-server:$TAG ./server
          docker build -t jethred/multi-worker:$TAG ./worker

          echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
          docker push jethred/multi-client:$TAG
          docker push jethred/multi-nginx:$TAG
          docker push jethred/multi-server:$TAG
          docker push jethred/multi-worker:$TAG

workflows:
  elastic-beanstalk-workflow:
    jobs:
      - buildAndTest
      - buildProdImages
      - aws-elastic-beanstalk/deploy:
          context: aws-creds_multi-docker
          environment-name: multi-docker-4
          label: version-<<pipeline.number>>
          filters:
            branches:
              only:
                - master
          requires:
            - buildProdImages
            - buildAndTest